### ISSUE TITLE
Allow arbitrary rules settings

### ISSUE THREAD

**Issue by Zannick** [Zannick/logic-graph#143]
The format would be like:

```yaml
rules:
    objective:
        default: true
        all_items: [...]
        all_bosses: [...]
    victory:
        default: Victory
        just_these_items: [...]
```

and any can be defined. In the settings file it would look like

```yaml
rules:
    objective: all_items
```

This generalizes #48.
