### ISSUE TITLE
Jump movement

### ISSUE THREAD

**Issue by Zannick** [Zannick/logic-graph#15]
That might be misleading to call it 'movement', but really the benefit of this would be just to enable moving from a lower height to a higher height when normally that's not possible (because the y-coords differ). I want to say:

```yaml
// A  D
// B--C
- name: A
  local:
  - to: D
    thru: [bx, by], [cx, cy]
    jumps: [0, 0, 4]
    jumps_down: [2, 0, 0]
```

`jumps_down` adds a small amount of delay to falling. `jumps` allows movement upward, where the speed is dependent on the jump speed for an available movement. Each of these has to be an int array of length equal to the length of the path between Spots, i.e. the number of thru points plus 1.

The jump speed in movements would be measured as the time it takes to jump upward one level on average.
